server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启丛注册动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #随意取名，但要唯一
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由
            #- After=2020-11-22T09:08:22.034+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id,\d+
            #- Host=**.atguigu.com
            #- Method=POST
            #- Query=username

        - id: payment_routh2 #随意取名，但要唯一
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由
            #- After=2020-11-22T09:08:22.034+08:00[Asia/Shanghai]

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #表示是否注册到服务中心，默认是true, false表示不向服务中心注册自己
    register-with-eureka: true
    #是否丛服务端抓取已有的注册信息，默认为true,单节点无所谓，集群必需设置为true,才能使用ribbon使用负载均衡，false表示自己端就是服务中心，我的职责是维护实例，并不需要检索服务
    fetchRegistry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/ #单机
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群

