server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #这个名字是一个通道的名称
          destination: studyExchange #表示要使用的exchange的名称定义
          content-type: application/json
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          #group: atguiguA

eureka:
  client:
    #表示是否注册到服务中心，默认是true, false表示不向服务中心注册自己
    register-with-eureka: true
    #是否丛服务端抓取已有的注册信息，默认为true,单节点无所谓，集群必需设置为true,才能使用ribbon使用负载均衡，false表示自己端就是服务中心，我的职责是维护实例，并不需要检索服务
    fetchRegistry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/ #单机
  #      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群
  instance:
    instance-id: receive-8802.com
    prefer-ip-address: true #访问路径可以显示IP
    #eureka客户端向发送心跳的等待时间上限，单位为秒(默认是30s)
    lease-renewal-interval-in-seconds: 2
    #eureka收到最后一次心跳等待时间上限，单位为秒(默认是90s),超过时间将踢除
    lease-expiration-duration-in-seconds: 5
